#!/bin/sh -e

./configure \
	--prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/bin \
	--datarootdir=/usr/share \
	--disable-example \
	MOUNT_FUSE_PATH=/usr/bin \
	UDEV_RULES_PATH=/usr/lib/udev

make
make install

# Remove fuse device file, it isn't needed
# and breaks the install
rm -r "${1:?}/dev"
